
package Calculadora_Basica_UI;

/*@author JoseDaniel*/
public class Calculadora extends javax.swing.JFrame {

    public Calculadora() {
        initComponents();
        //this.txtDatos.enable(false); Por si se quiere evitar que se escriba con el teclado en el campo de texto
        setLocationRelativeTo(null);//Esta linea de codigo lo que permite es centrar en la pantalla nuesta aplicación
    }
    
    
    
    //Objeto Global
Operaciones operaciones =new Operaciones();







    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNum11 = new javax.swing.JButton();
        btnNum14 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtDatos = new javax.swing.JTextField();
        bt1 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        bt0 = new javax.swing.JButton();
        btresta = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        btsuma = new javax.swing.JButton();
        btdivision = new javax.swing.JButton();
        btmulti = new javax.swing.JButton();
        btTotal = new javax.swing.JButton();
        btAC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        btnNum11.setText("1");

        btnNum14.setText("1");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Calculador_Basica/Imagenes/fondo_Calculadora.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora Básica");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMinimumSize(new java.awt.Dimension(440, 530));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDatos.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txtDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatosActionPerformed(evt);
            }
        });
        getContentPane().add(txtDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 62, 351, 60));

        bt1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt1.setText("1");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 185, 52, 52));

        bt3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt3.setText("3");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        getContentPane().add(bt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 185, 52, 52));

        bt2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt2.setText("2");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        getContentPane().add(bt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 185, 52, 52));

        bt4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt4.setText("4");
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });
        getContentPane().add(bt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 253, 52, 52));

        bt6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt6.setText("6");
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });
        getContentPane().add(bt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 253, 52, 52));

        bt5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt5.setText("5");
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });
        getContentPane().add(bt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 253, 52, 52));

        bt8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt8.setText("8");
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });
        getContentPane().add(bt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 321, 52, 52));

        bt9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt9.setText("9");
        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt9ActionPerformed(evt);
            }
        });
        getContentPane().add(bt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 321, 52, 52));

        bt0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt0.setText("0");
        bt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt0ActionPerformed(evt);
            }
        });
        getContentPane().add(bt0, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 389, 52, 52));

        btresta.setBackground(new java.awt.Color(255, 204, 204));
        btresta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btresta.setForeground(new java.awt.Color(0, 0, 255));
        btresta.setText("-");
        btresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrestaActionPerformed(evt);
            }
        });
        getContentPane().add(btresta, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 185, 50, 75));

        bt7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt7.setText("7");
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });
        getContentPane().add(bt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 321, 52, 52));

        btsuma.setBackground(new java.awt.Color(255, 204, 204));
        btsuma.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btsuma.setForeground(new java.awt.Color(0, 0, 255));
        btsuma.setText("+");
        btsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsumaActionPerformed(evt);
            }
        });
        getContentPane().add(btsuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 185, 50, 75));

        btdivision.setBackground(new java.awt.Color(255, 204, 204));
        btdivision.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btdivision.setForeground(new java.awt.Color(0, 0, 255));
        btdivision.setText("/");
        btdivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdivisionActionPerformed(evt);
            }
        });
        getContentPane().add(btdivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 276, 50, 75));

        btmulti.setBackground(new java.awt.Color(255, 204, 204));
        btmulti.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btmulti.setForeground(new java.awt.Color(0, 0, 255));
        btmulti.setText("*");
        btmulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmultiActionPerformed(evt);
            }
        });
        getContentPane().add(btmulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 276, 50, 75));

        btTotal.setBackground(new java.awt.Color(255, 0, 51));
        btTotal.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btTotal.setText("=");
        btTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTotalActionPerformed(evt);
            }
        });
        getContentPane().add(btTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 367, 115, 74));

        btAC.setBackground(new java.awt.Color(153, 255, 153));
        btAC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btAC.setText("AC");
        btAC.setToolTipText("");
        btAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btACActionPerformed(evt);
            }
        });
        getContentPane().add(btAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 119, 52));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calculadora Básica");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 24, 351, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("OPERACIONES");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 156, 115, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("VALORES");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 156, 186, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculadora_Basica_UI/fondo1.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // Asignando valor al boton del numero 1
        this.txtDatos.setText(this.txtDatos.getText()+1);
    }//GEN-LAST:event_bt1ActionPerformed
    
    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        // Asignando valor al boton del numero 2
        this.txtDatos.setText(this.txtDatos.getText()+2);
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        // Asignando valor al boton del numero 3
        this.txtDatos.setText(this.txtDatos.getText()+3);
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        // Asignando valor al boton del numero 4
        this.txtDatos.setText(this.txtDatos.getText()+4);
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        // Asignando valor al boton del numero 5
        this.txtDatos.setText(this.txtDatos.getText()+5);
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
        // Asignando valor al boton del numero 6
        this.txtDatos.setText(this.txtDatos.getText()+6);
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
        // Asignando valor al boton del numero 7
        this.txtDatos.setText(this.txtDatos.getText()+7);
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
        // Asignando valor al boton del numero 8
        this.txtDatos.setText(this.txtDatos.getText()+8);
    }//GEN-LAST:event_bt8ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
        // Asignando valor al boton del numero 9
        this.txtDatos.setText(this.txtDatos.getText()+9);
    }//GEN-LAST:event_bt9ActionPerformed

    private void bt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt0ActionPerformed
        // Asignando valor al boton del numero 
        this.txtDatos.setText(this.txtDatos.getText()+0);
    }//GEN-LAST:event_bt0ActionPerformed

    //Código de programación del botón de suma
    private void btsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsumaActionPerformed
        operador ="+";
        operaciones.setNumero1((Integer.parseInt(this.txtDatos.getText())));
        this.txtDatos.setText("");// Para que quede vacio a la hora de agregar otro número que desee sumar
    }//GEN-LAST:event_btsumaActionPerformed
    //Código del botón Total
    private void btTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTotalActionPerformed
        
        operaciones.setNumero2((Integer.parseInt(this.txtDatos.getText())));
        //El menú de operaciones
        switch (operador) {
            case "+":  
                resultado= operaciones.Sumar(operaciones.getNumero1(), operaciones.getNumero2()); 
                break;
            case "-":  
                resultado= operaciones.Restar(operaciones.getNumero1(), operaciones.getNumero2()); 
                break;
            case "*":  
                resultado= operaciones.Multiplicar(operaciones.getNumero1(), operaciones.getNumero2()); 
                break;
            case "/":  
                resultado= operaciones.Dividir(operaciones.getNumero1(), operaciones.getNumero2()); 
                break;
        }
        
        this.txtDatos.setText(String.valueOf(resultado));
        
        operador="=";
        
    }//GEN-LAST:event_btTotalActionPerformed
    //Código del botón Multiplicar
    private void btmultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmultiActionPerformed
        operador ="*";
        operaciones.setNumero1((Integer.parseInt(this.txtDatos.getText())));
        this.txtDatos.setText("");// Para que quede vacio a la hora de agregar otro número que desee multiplicar
    }//GEN-LAST:event_btmultiActionPerformed

    //Código del botón Borrar AC
    private void btACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btACActionPerformed
        //Se ponen todo los valores en blanco es decir los numero en 0 y el campo de texto vacio
        
        this.txtDatos.setText("");
        operaciones.setNumero1(0);
        operaciones.setNumero2(0);
        resultado=0;
        operador="";
    }//GEN-LAST:event_btACActionPerformed

        //Código del botón resta
    private void btrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrestaActionPerformed
        operador ="-";
        operaciones.setNumero1((Integer.parseInt(this.txtDatos.getText())));
        this.txtDatos.setText("");// Para que quede vacio a la hora de agregar otro número que desee restar
    }//GEN-LAST:event_btrestaActionPerformed

        //Código del botón de división
    private void btdivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdivisionActionPerformed
        operador ="/";
        operaciones.setNumero1((Integer.parseInt(this.txtDatos.getText())));
        this.txtDatos.setText("");// Para que quede vacio a la hora de agregar otro número que desee dividir
    }//GEN-LAST:event_btdivisionActionPerformed

    private void txtDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
                
            }
        });
    }

    
    
    String operador = ""; //Variable utilizada para saber cual operacion realizar 
    int resultado=0; //Variable utilizada para mostrar el resultado final de las operaciones de la calculadora
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt0;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btAC;
    private javax.swing.JButton btTotal;
    private javax.swing.JButton btdivision;
    private javax.swing.JButton btmulti;
    private javax.swing.JButton btnNum11;
    private javax.swing.JButton btnNum14;
    private javax.swing.JButton btresta;
    private javax.swing.JButton btsuma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtDatos;
    // End of variables declaration//GEN-END:variables
}
